-- MySQL Script generated by MySQL Workbench
-- 10/21/16 17:12:14
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema msg_cv
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema msg_cv
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `msg_cv` DEFAULT CHARACTER SET utf8 ;
USE `msg_cv` ;

-- -----------------------------------------------------
-- Table `msg_cv`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `msg_cv`.`user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(45) NOT NULL,
  `lastName` VARCHAR(45) NOT NULL,
  `dateOfBirth` VARCHAR(45) NOT NULL,
  `cnp` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `cnp_UNIQUE` (`cnp` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `msg_cv`.`cvuser`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `msg_cv`.`cvuser` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `userId` INT(11) NOT NULL,
  `cvTitle` VARCHAR(45) NOT NULL,
  `cvContent` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_userid_idx` (`userId` ASC),
  CONSTRAINT `fk_userid`
    FOREIGN KEY (`userId`)
    REFERENCES `msg_cv`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
